### ISSUE TITLE
esp_bt.h: No such file or directory

### ISSUE THREAD

**Issue by bmishra4** [Seeed-Studio/Grove_BMP280#2]
**C:\Users\Arduino\libraries\BLEDevice\src/BLEDevice.h:16:20: fatal error: esp_bt.h: No such file or directory**
 

M unable to compile the sketch, getting the above error.

**Comment by lanselambor** [comment]
@bmishra4  Please provide information about board and application you were using.

**Comment by ackPeng** [comment]
@bmishra4 Do you have any questions about this?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
