### ISSUE TITLE
Blocking the I2C bus

### ISSUE THREAD

**Issue by beicnet** [Seeed-Studio/Grove_BMP280#4]
If the sensor is not present or has been damaged while sketch starting or running, it will block/freeze the whole I2C bus and also the loop execution process.

**Comment by lanselambor** [comment]
@beicnet this is a common issue at i2c requesting data, however I agree that I2C bus should not be blocked in a program. I have modified the code to check data available before reading data, this could solve the blocking issue, please update your code and try again. Notice that if the sensor is not present or damaged the **init** function will return **false**, but getTemperature function will still return a data which is a invalid data.

**Comment by beicnet** [comment]
@lanselambor,

> I have modified the code to check data available before reading data, this could solve the blocking issue, please update your code and try again. Notice that if the sensor is not present or damaged the init function will return false

Thank you the first part is working as you stated.

> but getTemperature function will still return a data which is a invalid data.

Can you maybe implement something like, if the library temperature reading is `> -100` then the getTemperature and getPressure function will return 0?

Also, can you please make the library to be able to change the address of the sensor?

Primary with 0x77 by default
`bmp.init()`

Secondary with 0x76
`bmp.init(0x76)`

And the last one, can you do this all changes to the BME280 library too, or I need to open issue for that too?

Thank you! ;)

**Comment by beicnet** [comment]
Or maybe to implement some better error handling like:

```
float bmp_t;
float bmp_p;

void loop() {

int itRet = bmp.read();

  switch (itRet)
  {
    case BMP_OK:
      bmp_t = bmp.getTemperature;
      bmp_h = bmp.getPressure;
      break;
    default:
      bmp_t = 0.00;
      bmp_h = 0.00;
      break;
  }

delay(2000);

}
```

**Comment by lanselambor** [comment]
@beicnet Sorry for the late replying, has update the code for supporting i2c address setting, and for defined _INVALID_DATA as 999999, when BMP280 doesn't connected or broken, return temperature pressure and altitude value with _INVALID_DATA.

**Comment by lanselambor** [comment]
If module error occurs temperature humidity and altitude will all be 0.
